export enum PromotionType {
  AMOUNT_OFF_PRODUCT = 'AMOUNT_OFF_PRODUCT',
  AMOUNT_OFF_ORDER = 'AMOUNT_OFF_ORDER',
  PERCENT_OFF_PRODUCT = 'PERCENT_OFF_PRODUCT',
  PERCENT_OFF_ORDER = 'PERCENT_OFF_ORDER',
  BUY_X_GET_Y = 'BUY_X_GET_Y',
}
